/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_fhnw_ether_avion_Avion */

#ifndef _Included_ch_fhnw_ether_avion_Avion
#define _Included_ch_fhnw_ether_avion_Avion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderCreate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_fhnw_ether_avion_Avion_decoderCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_ether_avion_Avion_decoderDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetDuration
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetVideoFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetVideoFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetVideoWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetVideoWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetVideoHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetVideoHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderSeek
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_ether_avion_Avion_decoderSeek
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetNextAudioFrame
 * Signature: (JLjava/nio/FloatBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetNextAudioFrame
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetNextVideoFrame
 * Signature: (JLjava/nio/ByteBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetNextVideoFrame
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
